# Generated by Django 3.0.1 on 2020-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('project_image', models.ImageField(blank=True, upload_to='project_description_images')),
                ('project_type', models.CharField(choices=[('Computer_Vision', 'Computer_Vision'), ('Time_Series', 'Time_Series'), ('Other', 'Other')], default='Other', max_length=20)),
                ('url', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
