# Generated by Django 3.0.1 on 2020-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_project_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, default='long description'),
        ),
    ]
