# Generated by Django 3.0.5 on 2020-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_auto_20200114_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, default='short description'),
        ),
    ]
