# Generated by Django 3.0.5 on 2020-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0006_auto_20200413_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='longName',
            field=models.CharField(default='project long name', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='project short name', max_length=200),
        ),
    ]
