# Generated by Django 3.0.5 on 2020-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpsonCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simpson_input_picture', models.ImageField(blank=True, upload_to='simpsonCharacter/simpsonInputPictures/')),
                ('simpson_output_picture', models.ImageField(blank=True, upload_to='simpsonCharacter/simpsonOutputPictures/')),
            ],
        ),
    ]
