# Generated by Django 3.0.5 on 2020-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpsons_go_neural', '0002_auto_20200417_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpsoncharacter',
            name='simpson_input_picture',
            field=models.ImageField(blank=True, default='simpsonCharacter/simpsonInputPictures/simpsons.jpeg', upload_to='simpsonCharacter/simpsonInputPictures/'),
        ),
        migrations.AlterField(
            model_name='simpsoncharacter',
            name='simpson_output_picture',
            field=models.ImageField(blank=True, default='simpsonCharacter/simpsonOutputPictures/simpsons.jpeg', upload_to='simpsonCharacter/simpsonOutputPictures/'),
        ),
    ]
