# Generated by Django 3.0.1 on 2020-01-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PI_name', models.CharField(default='PI Name', max_length=200)),
                ('PI_position', models.CharField(default='PI Position', max_length=200)),
                ('group_name', models.CharField(default='e.g., Soft Matter', max_length=200)),
                ('group_def', models.CharField(default='e.g., Lab, Group, etc.', max_length=200)),
                ('group_short_description', models.CharField(default='e.g., Soft Matter at Interfaces', max_length=200)),
                ('group_long_description', models.TextField(blank=True, default='We do research on...')),
            ],
        ),
    ]
