# Generated by Django 3.0.1 on 2020-01-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicWebSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('contact_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('PI', 'PI'), ('Postdoc', 'Postdoc'), ('PhD', 'PhD'), ('Technician', 'Technician'), ('MSc', 'MSc'), ('Guest_PhD', 'Guest_PhD'), ('Guest_Student', 'Guest_Student')], default='PhD', max_length=20)),
                ('initial_year', models.IntegerField()),
                ('final_year', models.IntegerField()),
                ('main_image', models.ImageField(blank=True, upload_to='members_images')),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField()),
                ('year', models.IntegerField()),
                ('title', models.TextField()),
                ('journal', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('initialPage', models.IntegerField()),
                ('publication_type', models.CharField(choices=[('Paper', 'Paper'), ('Review', 'Review'), ('Chapter', 'Chapter'), ('Proceeding', 'Proceeding')], default='Paper', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, upload_to='research_field_images')),
            ],
        ),
    ]
