# Generated by Django 3.0.1 on 2020-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_input_picture', models.ImageField(upload_to='emotionrecognition/faceinputpictures/')),
                ('face_output_picture', models.ImageField(blank=True, upload_to='emotionrecognition/faceoutputpictures/')),
            ],
        ),
    ]
