# Generated by Django 3.0.1 on 2020-01-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_project_tutorial', models.TextField(blank=True)),
            ],
        ),
    ]
