# Generated by Django 3.0.5 on 2020-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_recognition', '0003_delete_faceproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemood',
            name='face_input_picture',
            field=models.ImageField(blank=True, upload_to='emotionrecognition/faceinputpictures/'),
        ),
    ]
